/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "seq_mult.v:26" *)
module seq_mult(p, rdy, clk, reset, a, b);
  (* src = "seq_mult.v:96" *)
  wire [4:0] _000_;
  (* src = "seq_mult.v:96" *)
  wire [15:0] _001_;
  (* src = "seq_mult.v:96" *)
  wire [15:0] _002_;
  (* src = "seq_mult.v:96" *)
  wire _003_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61" *)
  wire _004_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61" *)
  wire _005_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _006_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _007_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _008_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _009_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _010_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _011_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61" *)
  wire _012_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61" *)
  wire _013_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61" *)
  wire _014_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61" *)
  wire _015_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _016_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _017_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _018_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _019_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _020_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _021_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _022_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _023_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _024_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _025_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _026_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _027_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _028_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _029_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _030_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _031_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _032_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _033_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _034_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _035_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _036_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _037_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _038_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _039_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _040_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _041_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _042_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _043_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _044_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _045_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61" *)
  wire _046_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61" *)
  wire _047_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _048_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _049_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _050_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _051_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _052_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:71" *)
  wire _053_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61" *)
  wire _054_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61" *)
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  (* src = "seq_mult.v:33" *)
  input [7:0] a;
  (* src = "seq_mult.v:33" *)
  input [7:0] b;
  (* src = "seq_mult.v:32" *)
  input clk;
  (* src = "seq_mult.v:44" *)
  wire [4:0] ctr;
  (* src = "seq_mult.v:39" *)
  wire [15:0] multiplicand;
  (* src = "seq_mult.v:40" *)
  wire [7:0] multiplier;
  (* src = "seq_mult.v:35" *)
  output [15:0] p;
  (* src = "seq_mult.v:36" *)
  output rdy;
  (* src = "seq_mult.v:32" *)
  input reset;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'hb)
  ) _109_ (
    .I0(reset),
    .I1(ctr[3]),
    .O(_056_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h14)
  ) _110_ (
    .I0(reset),
    .I1(_108_),
    .I2(ctr[2]),
    .O(_000_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _111_ (
    .I0(ctr[1]),
    .I1(ctr[0]),
    .O(_108_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:46" *)
  LUT4 #(
    .INIT(16'h0708)
  ) _112_ (
    .I0(_057_),
    .I1(ctr[3]),
    .I2(reset),
    .I3(ctr[4]),
    .O(_000_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _113_ (
    .I0(_108_),
    .I1(ctr[2]),
    .O(_057_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h14)
  ) _114_ (
    .I0(reset),
    .I1(_057_),
    .I2(ctr[3]),
    .O(_000_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h14)
  ) _115_ (
    .I0(reset),
    .I1(ctr[1]),
    .I2(ctr[0]),
    .O(_000_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h1)
  ) _116_ (
    .I0(reset),
    .I1(ctr[0]),
    .O(_000_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h14)
  ) _117_ (
    .I0(reset),
    .I1(_058_),
    .I2(p[0]),
    .O(_002_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _118_ (
    .I0(_059_),
    .I1(multiplicand[0]),
    .O(_058_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h4)
  ) _119_ (
    .I0(_060_),
    .I1(_061_),
    .O(_059_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:62" *)
  LUT6 #(
    .INIT(64'h0000000000000000)
  ) _120_ (
    .I0(multiplier[7]),
    .I1(multiplier[6]),
    .I2(multiplier[3]),
    .I3(multiplier[2]),
    .I4(ctr[0]),
    .I5(ctr[2]),
    .O(_004_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:65" *)
  LUT6 #(
    .INIT(64'h555533330f0f00ff)
  ) _121_ (
    .I0(multiplier[7]),
    .I1(multiplier[6]),
    .I2(multiplier[3]),
    .I3(multiplier[2]),
    .I4(ctr[0]),
    .I5(ctr[2]),
    .O(_005_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:68" *)
  MUXF7 _122_ (
    .I0(_004_),
    .I1(_005_),
    .O(_060_),
    .S(ctr[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:72" *)
  LUT6 #(
    .INIT(64'hfffff0f0ffffff00)
  ) _123_ (
    .I0(multiplier[5]),
    .I1(multiplier[4]),
    .I2(multiplier[1]),
    .I3(multiplier[0]),
    .I4(ctr[1]),
    .I5(ctr[0]),
    .O(_006_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:75" *)
  LUT6 #(
    .INIT(64'hffffaaaaffffcccc)
  ) _124_ (
    .I0(multiplier[5]),
    .I1(multiplier[4]),
    .I2(multiplier[1]),
    .I3(multiplier[0]),
    .I4(ctr[1]),
    .I5(ctr[0]),
    .O(_007_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:78" *)
  LUT6 #(
    .INIT(64'h0000000000000000)
  ) _125_ (
    .I0(multiplier[5]),
    .I1(multiplier[4]),
    .I2(multiplier[1]),
    .I3(multiplier[0]),
    .I4(ctr[1]),
    .I5(ctr[0]),
    .O(_008_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:81" *)
  LUT6 #(
    .INIT(64'h0000000000000000)
  ) _126_ (
    .I0(multiplier[5]),
    .I1(multiplier[4]),
    .I2(multiplier[1]),
    .I3(multiplier[0]),
    .I4(ctr[1]),
    .I5(ctr[0]),
    .O(_009_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:84" *)
  MUXF7 _127_ (
    .I0(_006_),
    .I1(_007_),
    .O(_010_),
    .S(ctr[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:85" *)
  MUXF7 _128_ (
    .I0(_008_),
    .I1(_009_),
    .O(_011_),
    .S(ctr[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86" *)
  MUXF8 _129_ (
    .I0(_010_),
    .I1(_011_),
    .O(_061_),
    .S(ctr[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:62" *)
  LUT6 #(
    .INIT(64'h00000000a22a0880)
  ) _130_ (
    .I0(_059_),
    .I1(multiplicand[0]),
    .I2(_062_),
    .I3(p[0]),
    .I4(multiplicand[1]),
    .I5(reset),
    .O(_012_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:65" *)
  LUT6 #(
    .INIT(64'h000000005dd5f77f)
  ) _131_ (
    .I0(_059_),
    .I1(multiplicand[0]),
    .I2(_062_),
    .I3(p[0]),
    .I4(multiplicand[1]),
    .I5(reset),
    .O(_013_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:68" *)
  MUXF7 _132_ (
    .I0(_012_),
    .I1(_013_),
    .O(_002_[1]),
    .S(p[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56" *)
  LUT6 #(
    .INIT(64'h1000000000000000)
  ) _133_ (
    .I0(ctr[3]),
    .I1(ctr[4]),
    .I2(multiplier[7]),
    .I3(ctr[2]),
    .I4(ctr[1]),
    .I5(ctr[0]),
    .O(_062_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:46" *)
  LUT4 #(
    .INIT(16'h4114)
  ) _134_ (
    .I0(reset),
    .I1(_063_),
    .I2(_064_),
    .I3(p[2]),
    .O(_002_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56" *)
  LUT6 #(
    .INIT(64'hffe0ff1fffffffff)
  ) _135_ (
    .I0(multiplicand[0]),
    .I1(multiplicand[1]),
    .I2(_062_),
    .I3(_060_),
    .I4(multiplicand[2]),
    .I5(_061_),
    .O(_063_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:62" *)
  LUT6 #(
    .INIT(64'hffffffffffffffff)
  ) _136_ (
    .I0(p[0]),
    .I1(p[1]),
    .I2(_062_),
    .I3(multiplicand[1]),
    .I4(multiplicand[0]),
    .I5(_060_),
    .O(_014_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:65" *)
  LUT6 #(
    .INIT(64'hffffffff711733ff)
  ) _137_ (
    .I0(p[0]),
    .I1(p[1]),
    .I2(_062_),
    .I3(multiplicand[1]),
    .I4(multiplicand[0]),
    .I5(_060_),
    .O(_015_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:68" *)
  MUXF7 _138_ (
    .I0(_014_),
    .I1(_015_),
    .O(_064_),
    .S(_061_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56" *)
  LUT6 #(
    .INIT(64'h0071008e008e0071)
  ) _139_ (
    .I0(_063_),
    .I1(_064_),
    .I2(p[2]),
    .I3(reset),
    .I4(_065_),
    .I5(p[3]),
    .O(_002_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h6)
  ) _140_ (
    .I0(_066_),
    .I1(_067_),
    .O(_065_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56" *)
  LUT6 #(
    .INIT(64'h00fe000000000000)
  ) _141_ (
    .I0(multiplicand[2]),
    .I1(multiplicand[1]),
    .I2(multiplicand[0]),
    .I3(_060_),
    .I4(_061_),
    .I5(_062_),
    .O(_066_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h40)
  ) _142_ (
    .I0(_060_),
    .I1(_061_),
    .I2(multiplicand[3]),
    .O(_067_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56" *)
  LUT6 #(
    .INIT(64'h002b00d400d4002b)
  ) _143_ (
    .I0(_068_),
    .I1(_065_),
    .I2(p[3]),
    .I3(reset),
    .I4(_069_),
    .I5(p[4]),
    .O(_002_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hb2)
  ) _144_ (
    .I0(_063_),
    .I1(p[2]),
    .I2(_064_),
    .O(_068_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:72" *)
  LUT6 #(
    .INIT(64'hffffffffffffffff)
  ) _145_ (
    .I0(multiplicand[0]),
    .I1(multiplicand[1]),
    .I2(multiplicand[2]),
    .I3(multiplicand[3]),
    .I4(_062_),
    .I5(_060_),
    .O(_016_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:75" *)
  LUT6 #(
    .INIT(64'hffffffffffffffff)
  ) _146_ (
    .I0(multiplicand[0]),
    .I1(multiplicand[1]),
    .I2(multiplicand[2]),
    .I3(multiplicand[3]),
    .I4(_062_),
    .I5(_060_),
    .O(_017_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:78" *)
  LUT6 #(
    .INIT(64'hffffffff0001ffff)
  ) _147_ (
    .I0(multiplicand[0]),
    .I1(multiplicand[1]),
    .I2(multiplicand[2]),
    .I3(multiplicand[3]),
    .I4(_062_),
    .I5(_060_),
    .O(_018_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:81" *)
  LUT6 #(
    .INIT(64'hfffffffffffe0000)
  ) _148_ (
    .I0(multiplicand[0]),
    .I1(multiplicand[1]),
    .I2(multiplicand[2]),
    .I3(multiplicand[3]),
    .I4(_062_),
    .I5(_060_),
    .O(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:84" *)
  MUXF7 _149_ (
    .I0(_016_),
    .I1(_017_),
    .O(_020_),
    .S(multiplicand[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:85" *)
  MUXF7 _150_ (
    .I0(_018_),
    .I1(_019_),
    .O(_021_),
    .S(multiplicand[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86" *)
  MUXF8 _151_ (
    .I0(_020_),
    .I1(_021_),
    .O(_069_),
    .S(_061_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:46" *)
  LUT4 #(
    .INIT(16'h010e)
  ) _152_ (
    .I0(_070_),
    .I1(_074_),
    .I2(reset),
    .I3(_073_),
    .O(_002_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h60)
  ) _153_ (
    .I0(_071_),
    .I1(_072_),
    .I2(p[5]),
    .O(_070_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h40)
  ) _154_ (
    .I0(_060_),
    .I1(_061_),
    .I2(multiplicand[5]),
    .O(_071_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:72" *)
  LUT6 #(
    .INIT(64'h0000000000000000)
  ) _155_ (
    .I0(multiplicand[0]),
    .I1(multiplicand[1]),
    .I2(multiplicand[2]),
    .I3(multiplicand[3]),
    .I4(multiplicand[4]),
    .I5(_062_),
    .O(_022_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:75" *)
  LUT6 #(
    .INIT(64'hfffffffe00000000)
  ) _156_ (
    .I0(multiplicand[0]),
    .I1(multiplicand[1]),
    .I2(multiplicand[2]),
    .I3(multiplicand[3]),
    .I4(multiplicand[4]),
    .I5(_062_),
    .O(_023_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:78" *)
  LUT6 #(
    .INIT(64'h0000000000000000)
  ) _157_ (
    .I0(multiplicand[0]),
    .I1(multiplicand[1]),
    .I2(multiplicand[2]),
    .I3(multiplicand[3]),
    .I4(multiplicand[4]),
    .I5(_062_),
    .O(_024_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:81" *)
  LUT6 #(
    .INIT(64'h0000000000000000)
  ) _158_ (
    .I0(multiplicand[0]),
    .I1(multiplicand[1]),
    .I2(multiplicand[2]),
    .I3(multiplicand[3]),
    .I4(multiplicand[4]),
    .I5(_062_),
    .O(_025_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:84" *)
  MUXF7 _159_ (
    .I0(_022_),
    .I1(_023_),
    .O(_026_),
    .S(_061_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:85" *)
  MUXF7 _160_ (
    .I0(_024_),
    .I1(_025_),
    .O(_027_),
    .S(_061_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86" *)
  MUXF8 _161_ (
    .I0(_026_),
    .I1(_027_),
    .O(_072_),
    .S(_060_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:72" *)
  LUT6 #(
    .INIT(64'hd0fdf0ff50f5d0fd)
  ) _162_ (
    .I0(p[3]),
    .I1(_063_),
    .I2(_069_),
    .I3(p[4]),
    .I4(p[2]),
    .I5(_064_),
    .O(_028_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:75" *)
  LUT6 #(
    .INIT(64'h40f450f500f040f4)
  ) _163_ (
    .I0(p[3]),
    .I1(_063_),
    .I2(_069_),
    .I3(p[4]),
    .I4(p[2]),
    .I5(_064_),
    .O(_029_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:78" *)
  LUT6 #(
    .INIT(64'h40f450f500f040f4)
  ) _164_ (
    .I0(p[3]),
    .I1(_063_),
    .I2(_069_),
    .I3(p[4]),
    .I4(p[2]),
    .I5(_064_),
    .O(_030_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:81" *)
  LUT6 #(
    .INIT(64'hd0fdf0ff50f5d0fd)
  ) _165_ (
    .I0(p[3]),
    .I1(_063_),
    .I2(_069_),
    .I3(p[4]),
    .I4(p[2]),
    .I5(_064_),
    .O(_031_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:84" *)
  MUXF7 _166_ (
    .I0(_028_),
    .I1(_029_),
    .O(_032_),
    .S(_066_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:85" *)
  MUXF7 _167_ (
    .I0(_030_),
    .I1(_031_),
    .O(_033_),
    .S(_066_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86" *)
  MUXF8 _168_ (
    .I0(_032_),
    .I1(_033_),
    .O(_073_),
    .S(_067_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h41)
  ) _169_ (
    .I0(p[5]),
    .I1(_072_),
    .I2(_071_),
    .O(_074_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd17698305)
  ) _170_ (
    .I0(_075_),
    .I1(_070_),
    .I2(reset),
    .I3(_076_),
    .I4(p[6]),
    .O(_002_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h1)
  ) _171_ (
    .I0(_073_),
    .I1(_074_),
    .O(_075_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h4b)
  ) _172_ (
    .I0(_078_),
    .I1(_062_),
    .I2(_077_),
    .O(_076_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h40)
  ) _173_ (
    .I0(_060_),
    .I1(_061_),
    .I2(multiplicand[6]),
    .O(_077_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:72" *)
  LUT6 #(
    .INIT(64'hffffffffffffffff)
  ) _174_ (
    .I0(multiplicand[0]),
    .I1(multiplicand[1]),
    .I2(multiplicand[2]),
    .I3(multiplicand[3]),
    .I4(multiplicand[4]),
    .I5(multiplicand[5]),
    .O(_034_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:75" *)
  LUT6 #(
    .INIT(64'h0000000000000001)
  ) _175_ (
    .I0(multiplicand[0]),
    .I1(multiplicand[1]),
    .I2(multiplicand[2]),
    .I3(multiplicand[3]),
    .I4(multiplicand[4]),
    .I5(multiplicand[5]),
    .O(_035_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:78" *)
  LUT6 #(
    .INIT(64'hffffffffffffffff)
  ) _176_ (
    .I0(multiplicand[0]),
    .I1(multiplicand[1]),
    .I2(multiplicand[2]),
    .I3(multiplicand[3]),
    .I4(multiplicand[4]),
    .I5(multiplicand[5]),
    .O(_036_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:81" *)
  LUT6 #(
    .INIT(64'hffffffffffffffff)
  ) _177_ (
    .I0(multiplicand[0]),
    .I1(multiplicand[1]),
    .I2(multiplicand[2]),
    .I3(multiplicand[3]),
    .I4(multiplicand[4]),
    .I5(multiplicand[5]),
    .O(_037_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:84" *)
  MUXF7 _178_ (
    .I0(_034_),
    .I1(_035_),
    .O(_038_),
    .S(_061_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:85" *)
  MUXF7 _179_ (
    .I0(_036_),
    .I1(_037_),
    .O(_039_),
    .S(_061_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86" *)
  MUXF8 _180_ (
    .I0(_038_),
    .I1(_039_),
    .O(_078_),
    .S(_060_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h4)
  ) _181_ (
    .I0(reset),
    .I1(_079_),
    .O(_002_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56" *)
  LUT6 #(
    .INIT(64'h10f1ef0eef0e10f1)
  ) _182_ (
    .I0(_075_),
    .I1(_070_),
    .I2(_076_),
    .I3(p[6]),
    .I4(_080_),
    .I5(p[7]),
    .O(_079_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:46" *)
  LUT4 #(
    .INIT(16'hb04f)
  ) _183_ (
    .I0(_077_),
    .I1(_078_),
    .I2(_062_),
    .I3(_081_),
    .O(_080_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h40)
  ) _184_ (
    .I0(_060_),
    .I1(_061_),
    .I2(multiplicand[7]),
    .O(_081_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:46" *)
  LUT4 #(
    .INIT(16'h010e)
  ) _185_ (
    .I0(_083_),
    .I1(_085_),
    .I2(reset),
    .I3(_082_),
    .O(_002_[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56" *)
  LUT6 #(
    .INIT(64'h0c8e0c8e0c8e8ecf)
  ) _186_ (
    .I0(_076_),
    .I1(_080_),
    .I2(p[7]),
    .I3(p[6]),
    .I4(_070_),
    .I5(_075_),
    .O(_082_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56" *)
  LUT6 #(
    .INIT(64'h10ffef0000000000)
  ) _187_ (
    .I0(_077_),
    .I1(_081_),
    .I2(_078_),
    .I3(_062_),
    .I4(_084_),
    .I5(p[8]),
    .O(_083_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h40)
  ) _188_ (
    .I0(_060_),
    .I1(_061_),
    .I2(multiplicand[8]),
    .O(_084_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56" *)
  LUT6 #(
    .INIT(64'h0000ef00000010ff)
  ) _189_ (
    .I0(_077_),
    .I1(_081_),
    .I2(_078_),
    .I3(_062_),
    .I4(p[8]),
    .I5(_084_),
    .O(_085_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd17698305)
  ) _190_ (
    .I0(_086_),
    .I1(_083_),
    .I2(reset),
    .I3(_087_),
    .I4(p[9]),
    .O(_002_[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:72" *)
  LUT6 #(
    .INIT(64'h00abffff000000ab)
  ) _191_ (
    .I0(_070_),
    .I1(_073_),
    .I2(_074_),
    .I3(_076_),
    .I4(_080_),
    .I5(p[7]),
    .O(_040_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:75" *)
  LUT6 #(
    .INIT(64'habffffff0000abff)
  ) _192_ (
    .I0(_070_),
    .I1(_073_),
    .I2(_074_),
    .I3(_076_),
    .I4(_080_),
    .I5(p[7]),
    .O(_041_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:78" *)
  LUT6 #(
    .INIT(64'h0000000000000000)
  ) _193_ (
    .I0(_070_),
    .I1(_073_),
    .I2(_074_),
    .I3(_076_),
    .I4(_080_),
    .I5(p[7]),
    .O(_042_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:81" *)
  LUT6 #(
    .INIT(64'h0000000000000000)
  ) _194_ (
    .I0(_070_),
    .I1(_073_),
    .I2(_074_),
    .I3(_076_),
    .I4(_080_),
    .I5(p[7]),
    .O(_043_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:84" *)
  MUXF7 _195_ (
    .I0(_040_),
    .I1(_041_),
    .O(_044_),
    .S(p[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:85" *)
  MUXF7 _196_ (
    .I0(_042_),
    .I1(_043_),
    .O(_045_),
    .S(p[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86" *)
  MUXF8 _197_ (
    .I0(_044_),
    .I1(_045_),
    .O(_086_),
    .S(_085_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56" *)
  LUT6 #(
    .INIT(64'hfeff00000100ffff)
  ) _198_ (
    .I0(_077_),
    .I1(_081_),
    .I2(_084_),
    .I3(_078_),
    .I4(_062_),
    .I5(_088_),
    .O(_087_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h40)
  ) _199_ (
    .I0(_060_),
    .I1(_061_),
    .I2(multiplicand[9]),
    .O(_088_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h1)
  ) _200_ (
    .I0(_089_),
    .I1(reset),
    .O(_002_[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56" *)
  LUT6 #(
    .INIT(64'h10f1ef0eef0e10f1)
  ) _201_ (
    .I0(_086_),
    .I1(_083_),
    .I2(_087_),
    .I3(p[9]),
    .I4(_090_),
    .I5(p[10]),
    .O(_089_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h6)
  ) _202_ (
    .I0(_091_),
    .I1(_092_),
    .O(_090_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56" *)
  LUT6 #(
    .INIT(64'hfffeffff00000000)
  ) _203_ (
    .I0(_081_),
    .I1(_084_),
    .I2(_088_),
    .I3(_077_),
    .I4(_078_),
    .I5(_062_),
    .O(_091_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h40)
  ) _204_ (
    .I0(_060_),
    .I1(_061_),
    .I2(multiplicand[10]),
    .O(_092_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:46" *)
  LUT4 #(
    .INIT(16'h0e01)
  ) _205_ (
    .I0(_094_),
    .I1(_097_),
    .I2(reset),
    .I3(_093_),
    .O(_002_[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56" *)
  LUT6 #(
    .INIT(64'hfba2fba2fba2ba20)
  ) _206_ (
    .I0(_090_),
    .I1(_087_),
    .I2(p[9]),
    .I3(p[10]),
    .I4(_083_),
    .I5(_086_),
    .O(_093_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h41)
  ) _207_ (
    .I0(p[11]),
    .I1(_096_),
    .I2(_095_),
    .O(_094_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _208_ (
    .I0(_059_),
    .I1(multiplicand[11]),
    .O(_095_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:62" *)
  LUT6 #(
    .INIT(64'h0000000000000000)
  ) _209_ (
    .I0(_081_),
    .I1(_084_),
    .I2(_088_),
    .I3(_092_),
    .I4(_077_),
    .I5(_078_),
    .O(_046_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:65" *)
  LUT6 #(
    .INIT(64'hfffffffeffffffff)
  ) _210_ (
    .I0(_081_),
    .I1(_084_),
    .I2(_088_),
    .I3(_092_),
    .I4(_077_),
    .I5(_078_),
    .O(_047_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:68" *)
  MUXF7 _211_ (
    .I0(_046_),
    .I1(_047_),
    .O(_096_),
    .S(_062_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h60)
  ) _212_ (
    .I0(_095_),
    .I1(_096_),
    .I2(p[11]),
    .O(_097_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:46" *)
  LUT4 #(
    .INIT(16'h0e01)
  ) _213_ (
    .I0(_098_),
    .I1(_101_),
    .I2(reset),
    .I3(_102_),
    .O(_002_[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h90)
  ) _214_ (
    .I0(_099_),
    .I1(_100_),
    .I2(p[12]),
    .O(_098_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h07)
  ) _215_ (
    .I0(_062_),
    .I1(_095_),
    .I2(_096_),
    .O(_099_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _216_ (
    .I0(_059_),
    .I1(multiplicand[12]),
    .O(_100_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h14)
  ) _217_ (
    .I0(p[12]),
    .I1(_099_),
    .I2(_100_),
    .O(_101_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:72" *)
  LUT6 #(
    .INIT(64'h5545440445440400)
  ) _218_ (
    .I0(_094_),
    .I1(_090_),
    .I2(_087_),
    .I3(p[9]),
    .I4(p[10]),
    .I5(_086_),
    .O(_048_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:75" *)
  LUT6 #(
    .INIT(64'h5545440455454404)
  ) _219_ (
    .I0(_094_),
    .I1(_090_),
    .I2(_087_),
    .I3(p[9]),
    .I4(p[10]),
    .I5(_086_),
    .O(_049_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:78" *)
  LUT6 #(
    .INIT(64'h5555555555555555)
  ) _220_ (
    .I0(_094_),
    .I1(_090_),
    .I2(_087_),
    .I3(p[9]),
    .I4(p[10]),
    .I5(_086_),
    .O(_050_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:81" *)
  LUT6 #(
    .INIT(64'h5555555555555555)
  ) _221_ (
    .I0(_094_),
    .I1(_090_),
    .I2(_087_),
    .I3(p[9]),
    .I4(p[10]),
    .I5(_086_),
    .O(_051_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:84" *)
  MUXF7 _222_ (
    .I0(_048_),
    .I1(_049_),
    .O(_052_),
    .S(_083_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:85" *)
  MUXF7 _223_ (
    .I0(_050_),
    .I1(_051_),
    .O(_053_),
    .S(_083_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86" *)
  MUXF8 _224_ (
    .I0(_052_),
    .I1(_053_),
    .O(_102_),
    .S(_097_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:46" *)
  LUT4 #(
    .INIT(16'h4114)
  ) _225_ (
    .I0(reset),
    .I1(_103_),
    .I2(_104_),
    .I3(p[13]),
    .O(_002_[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h0e)
  ) _226_ (
    .I0(_102_),
    .I1(_098_),
    .I2(_101_),
    .O(_103_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd1274032896)
  ) _227_ (
    .I0(multiplicand[12]),
    .I1(_099_),
    .I2(multiplicand[13]),
    .I3(_062_),
    .I4(_059_),
    .O(_104_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56" *)
  LUT6 #(
    .INIT(64'h00e80017001700e8)
  ) _228_ (
    .I0(_103_),
    .I1(_104_),
    .I2(p[13]),
    .I3(reset),
    .I4(_105_),
    .I5(p[14]),
    .O(_002_[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56" *)
  LUT6 #(
    .INIT(64'h10ffef000f000f00)
  ) _229_ (
    .I0(multiplicand[12]),
    .I1(multiplicand[13]),
    .I2(_099_),
    .I3(_062_),
    .I4(multiplicand[14]),
    .I5(_059_),
    .O(_105_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56" *)
  LUT6 #(
    .INIT(64'h0708080708070708)
  ) _230_ (
    .I0(_059_),
    .I1(multiplicand[15]),
    .I2(reset),
    .I3(_106_),
    .I4(_107_),
    .I5(p[15]),
    .O(_002_[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:62" *)
  LUT6 #(
    .INIT(64'hfffefe00ffe0e000)
  ) _231_ (
    .I0(_098_),
    .I1(_102_),
    .I2(_104_),
    .I3(_105_),
    .I4(p[14]),
    .I5(p[13]),
    .O(_054_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:65" *)
  LUT6 #(
    .INIT(64'hfff0f000ff000000)
  ) _232_ (
    .I0(_098_),
    .I1(_102_),
    .I2(_104_),
    .I3(_105_),
    .I4(p[14]),
    .I5(p[13]),
    .O(_055_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:68" *)
  MUXF7 _233_ (
    .I0(_054_),
    .I1(_055_),
    .O(_106_),
    .S(_101_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56" *)
  LUT6 #(
    .INIT(64'hfe000000ffff0000)
  ) _234_ (
    .I0(multiplicand[12]),
    .I1(multiplicand[13]),
    .I2(multiplicand[14]),
    .I3(_059_),
    .I4(_062_),
    .I5(_099_),
    .O(_107_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h0e)
  ) _235_ (
    .I0(rdy),
    .I1(ctr[3]),
    .I2(reset),
    .O(_003_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _236_ (
    .I0(reset),
    .I1(b[0]),
    .O(_001_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _237_ (
    .I0(multiplicand[0]),
    .I1(b[1]),
    .I2(reset),
    .O(_001_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _238_ (
    .I0(multiplicand[1]),
    .I1(b[2]),
    .I2(reset),
    .O(_001_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _239_ (
    .I0(multiplicand[2]),
    .I1(b[3]),
    .I2(reset),
    .O(_001_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _240_ (
    .I0(multiplicand[3]),
    .I1(b[4]),
    .I2(reset),
    .O(_001_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _241_ (
    .I0(multiplicand[4]),
    .I1(b[5]),
    .I2(reset),
    .O(_001_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _242_ (
    .I0(multiplicand[5]),
    .I1(b[6]),
    .I2(reset),
    .O(_001_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _243_ (
    .I0(multiplicand[6]),
    .I1(b[7]),
    .I2(reset),
    .O(_001_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _244_ (
    .I0(multiplicand[7]),
    .I1(b[7]),
    .I2(reset),
    .O(_001_[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _245_ (
    .I0(multiplicand[8]),
    .I1(b[7]),
    .I2(reset),
    .O(_001_[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _246_ (
    .I0(multiplicand[9]),
    .I1(b[7]),
    .I2(reset),
    .O(_001_[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _247_ (
    .I0(multiplicand[10]),
    .I1(b[7]),
    .I2(reset),
    .O(_001_[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _248_ (
    .I0(multiplicand[11]),
    .I1(b[7]),
    .I2(reset),
    .O(_001_[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _249_ (
    .I0(multiplicand[12]),
    .I1(b[7]),
    .I2(reset),
    .O(_001_[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _250_ (
    .I0(multiplicand[13]),
    .I1(b[7]),
    .I2(reset),
    .O(_001_[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _251_ (
    .I0(multiplicand[14]),
    .I1(b[7]),
    .I2(reset),
    .O(_001_[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:96|/usr/bin/../share/yosys/xilinx/ff_map.v:26" *)
  FDRE #(
    .INIT(1'h0)
  ) _252_ (
    .C(clk),
    .CE(1'h1),
    .D(_000_[0]),
    .Q(ctr[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:96|/usr/bin/../share/yosys/xilinx/ff_map.v:26" *)
  FDRE #(
    .INIT(1'h0)
  ) _253_ (
    .C(clk),
    .CE(1'h1),
    .D(_000_[1]),
    .Q(ctr[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:96|/usr/bin/../share/yosys/xilinx/ff_map.v:26" *)
  FDRE #(
    .INIT(1'h0)
  ) _254_ (
    .C(clk),
    .CE(1'h1),
    .D(_000_[2]),
    .Q(ctr[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:96|/usr/bin/../share/yosys/xilinx/ff_map.v:26" *)
  FDRE #(
    .INIT(1'h0)
  ) _255_ (
    .C(clk),
    .CE(1'h1),
    .D(_000_[3]),
    .Q(ctr[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:96|/usr/bin/../share/yosys/xilinx/ff_map.v:26" *)
  FDRE #(
    .INIT(1'h0)
  ) _256_ (
    .C(clk),
    .CE(1'h1),
    .D(_000_[4]),
    .Q(ctr[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:96|/usr/bin/../share/yosys/xilinx/ff_map.v:26" *)
  FDRE #(
    .INIT(1'h0)
  ) _257_ (
    .C(clk),
    .CE(1'h1),
    .D(_003_),
    .Q(rdy),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _258_ (
    .C(clk),
    .CE(_056_),
    .D(_001_[0]),
    .Q(multiplicand[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _259_ (
    .C(clk),
    .CE(_056_),
    .D(_001_[1]),
    .Q(multiplicand[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _260_ (
    .C(clk),
    .CE(_056_),
    .D(_001_[2]),
    .Q(multiplicand[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _261_ (
    .C(clk),
    .CE(_056_),
    .D(_001_[3]),
    .Q(multiplicand[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _262_ (
    .C(clk),
    .CE(_056_),
    .D(_001_[4]),
    .Q(multiplicand[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _263_ (
    .C(clk),
    .CE(_056_),
    .D(_001_[5]),
    .Q(multiplicand[5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _264_ (
    .C(clk),
    .CE(_056_),
    .D(_001_[6]),
    .Q(multiplicand[6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _265_ (
    .C(clk),
    .CE(_056_),
    .D(_001_[7]),
    .Q(multiplicand[7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _266_ (
    .C(clk),
    .CE(_056_),
    .D(_001_[8]),
    .Q(multiplicand[8]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _267_ (
    .C(clk),
    .CE(_056_),
    .D(_001_[9]),
    .Q(multiplicand[9]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _268_ (
    .C(clk),
    .CE(_056_),
    .D(_001_[10]),
    .Q(multiplicand[10]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _269_ (
    .C(clk),
    .CE(_056_),
    .D(_001_[11]),
    .Q(multiplicand[11]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _270_ (
    .C(clk),
    .CE(_056_),
    .D(_001_[12]),
    .Q(multiplicand[12]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _271_ (
    .C(clk),
    .CE(_056_),
    .D(_001_[13]),
    .Q(multiplicand[13]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _272_ (
    .C(clk),
    .CE(_056_),
    .D(_001_[14]),
    .Q(multiplicand[14]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _273_ (
    .C(clk),
    .CE(_056_),
    .D(_001_[15]),
    .Q(multiplicand[15]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _274_ (
    .C(clk),
    .CE(reset),
    .D(a[0]),
    .Q(multiplier[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _275_ (
    .C(clk),
    .CE(reset),
    .D(a[1]),
    .Q(multiplier[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _276_ (
    .C(clk),
    .CE(reset),
    .D(a[2]),
    .Q(multiplier[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _277_ (
    .C(clk),
    .CE(reset),
    .D(a[3]),
    .Q(multiplier[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _278_ (
    .C(clk),
    .CE(reset),
    .D(a[4]),
    .Q(multiplier[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _279_ (
    .C(clk),
    .CE(reset),
    .D(a[5]),
    .Q(multiplier[5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _280_ (
    .C(clk),
    .CE(reset),
    .D(a[6]),
    .Q(multiplier[6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _281_ (
    .C(clk),
    .CE(reset),
    .D(a[7]),
    .Q(multiplier[7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _282_ (
    .C(clk),
    .CE(_056_),
    .D(_002_[0]),
    .Q(p[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _283_ (
    .C(clk),
    .CE(_056_),
    .D(_002_[1]),
    .Q(p[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _284_ (
    .C(clk),
    .CE(_056_),
    .D(_002_[2]),
    .Q(p[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _285_ (
    .C(clk),
    .CE(_056_),
    .D(_002_[3]),
    .Q(p[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _286_ (
    .C(clk),
    .CE(_056_),
    .D(_002_[4]),
    .Q(p[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _287_ (
    .C(clk),
    .CE(_056_),
    .D(_002_[5]),
    .Q(p[5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _288_ (
    .C(clk),
    .CE(_056_),
    .D(_002_[6]),
    .Q(p[6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _289_ (
    .C(clk),
    .CE(_056_),
    .D(_002_[7]),
    .Q(p[7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _290_ (
    .C(clk),
    .CE(_056_),
    .D(_002_[8]),
    .Q(p[8]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _291_ (
    .C(clk),
    .CE(_056_),
    .D(_002_[9]),
    .Q(p[9]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _292_ (
    .C(clk),
    .CE(_056_),
    .D(_002_[10]),
    .Q(p[10]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _293_ (
    .C(clk),
    .CE(_056_),
    .D(_002_[11]),
    .Q(p[11]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _294_ (
    .C(clk),
    .CE(_056_),
    .D(_002_[12]),
    .Q(p[12]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _295_ (
    .C(clk),
    .CE(_056_),
    .D(_002_[13]),
    .Q(p[13]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _296_ (
    .C(clk),
    .CE(_056_),
    .D(_002_[14]),
    .Q(p[14]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _297_ (
    .C(clk),
    .CE(_056_),
    .D(_002_[15]),
    .Q(p[15]),
    .R(1'h0)
  );
endmodule
