/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "seq_mult.v:25" *)
module seq_mult(p, rdy, clk, reset, a, b);
  (* src = "seq_mult.v:62" *)
  wire [4:0] _000_;
  (* src = "seq_mult.v:62" *)
  wire [15:0] _001_;
  (* src = "seq_mult.v:62" *)
  wire [15:0] _002_;
  (* src = "seq_mult.v:62" *)
  wire _003_;
  (* src = "seq_mult.v:125" *)
  wire _004_;
  (* src = "seq_mult.v:125" *)
  wire _005_;
  (* src = "seq_mult.v:125" *)
  wire _006_;
  (* src = "seq_mult.v:125" *)
  wire _007_;
  (* src = "seq_mult.v:125" *)
  wire _008_;
  (* src = "seq_mult.v:125" *)
  wire _009_;
  (* src = "seq_mult.v:125" *)
  wire _010_;
  (* src = "seq_mult.v:125" *)
  wire _011_;
  (* src = "seq_mult.v:125" *)
  wire _012_;
  (* src = "seq_mult.v:125" *)
  wire _013_;
  (* src = "seq_mult.v:125" *)
  wire _014_;
  (* src = "seq_mult.v:125" *)
  wire _015_;
  (* src = "seq_mult.v:125" *)
  wire _016_;
  (* src = "seq_mult.v:125" *)
  wire _017_;
  (* src = "seq_mult.v:125" *)
  wire _018_;
  (* src = "seq_mult.v:125" *)
  wire _019_;
  (* src = "seq_mult.v:126" *)
  wire _020_;
  (* src = "seq_mult.v:126" *)
  wire _021_;
  (* src = "seq_mult.v:126" *)
  wire _022_;
  (* src = "seq_mult.v:126" *)
  wire _023_;
  (* src = "seq_mult.v:126" *)
  wire _024_;
  (* src = "seq_mult.v:126" *)
  wire _025_;
  (* src = "seq_mult.v:126" *)
  wire _026_;
  (* src = "seq_mult.v:126" *)
  wire _027_;
  (* src = "seq_mult.v:126" *)
  wire _028_;
  (* src = "seq_mult.v:126" *)
  wire _029_;
  (* src = "seq_mult.v:126" *)
  wire _030_;
  (* src = "seq_mult.v:126" *)
  wire _031_;
  (* src = "seq_mult.v:126" *)
  wire _032_;
  (* src = "seq_mult.v:126" *)
  wire _033_;
  (* src = "seq_mult.v:126" *)
  wire _034_;
  (* src = "seq_mult.v:126" *)
  wire _035_;
  (* src = "seq_mult.v:76|/usr/bin/../share/yosys/xilinx/arith_map.v:160" *)
  wire _036_;
  (* src = "seq_mult.v:76|/usr/bin/../share/yosys/xilinx/arith_map.v:160" *)
  wire _037_;
  (* src = "seq_mult.v:76|/usr/bin/../share/yosys/xilinx/arith_map.v:160" *)
  wire _038_;
  (* src = "seq_mult.v:76|/usr/bin/../share/yosys/xilinx/arith_map.v:160" *)
  wire _039_;
  (* src = "seq_mult.v:76|/usr/bin/../share/yosys/xilinx/arith_map.v:160" *)
  wire _040_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _041_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _042_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _043_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _044_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _045_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _046_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _047_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _048_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _049_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _050_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _051_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _052_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _053_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _054_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _055_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _056_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _057_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _058_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _059_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _060_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _061_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _062_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _063_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _064_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _065_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _066_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _067_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _068_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _069_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _070_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _071_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _072_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _073_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _074_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _075_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _076_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _077_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _078_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _079_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _080_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _081_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _082_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _083_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _084_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _085_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:337" *)
  wire _086_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _087_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _088_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _089_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _090_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _091_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _092_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _093_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _094_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _095_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _096_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _097_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _098_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _099_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _100_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _101_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _102_;
  (* src = "seq_mult.v:89|/usr/bin/../share/yosys/xilinx/arith_map.v:336" *)
  wire _103_;
  wire _104_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61" *)
  wire _105_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61" *)
  wire _106_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61" *)
  wire _107_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61" *)
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  (* src = "seq_mult.v:76|/usr/bin/../share/yosys/xilinx/arith_map.v:339" *)
  wire [4:0] _145_;
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:339" *)
  wire [15:0] _146_;
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:339" *)
  wire [15:0] _147_;
  (* src = "seq_mult.v:89|/usr/bin/../share/yosys/xilinx/arith_map.v:339" *)
  wire [4:0] _148_;
  (* src = "seq_mult.v:32" *)
  input [7:0] a;
  (* src = "seq_mult.v:50" *)
  wire [15:0] acc_in2;
  (* src = "seq_mult.v:32" *)
  input [7:0] b;
  (* src = "seq_mult.v:31" *)
  input clk;
  (* src = "seq_mult.v:42" *)
  wire [4:0] ctr;
  (* src = "seq_mult.v:38" *)
  reg [15:0] multiplicand;
  (* src = "seq_mult.v:39" *)
  reg [7:0] multiplier;
  (* src = "seq_mult.v:56" *)
  wire [15:0] mux_in1;
  (* src = "seq_mult.v:57" *)
  wire [15:0] mux_in2;
  (* src = "seq_mult.v:34" *)
  output [15:0] p;
  (* src = "seq_mult.v:35" *)
  output rdy;
  (* src = "seq_mult.v:31" *)
  input reset;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h4)
  ) _149_ (
    .I0(_141_),
    .I1(multiplicand[0]),
    .O(_001_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56" *)
  LUT6 #(
    .INIT(64'hfffeffff00000000)
  ) _150_ (
    .I0(ctr[4]),
    .I1(ctr[2]),
    .I2(ctr[1]),
    .I3(ctr[0]),
    .I4(ctr[3]),
    .I5(_104_),
    .O(_141_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _151_ (
    .I0(multiplicand[1]),
    .I1(multiplicand[0]),
    .I2(_141_),
    .O(_001_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _152_ (
    .I0(multiplicand[2]),
    .I1(multiplicand[1]),
    .I2(_141_),
    .O(_001_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _153_ (
    .I0(multiplicand[3]),
    .I1(multiplicand[2]),
    .I2(_141_),
    .O(_001_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _154_ (
    .I0(multiplicand[4]),
    .I1(multiplicand[3]),
    .I2(_141_),
    .O(_001_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _155_ (
    .I0(multiplicand[5]),
    .I1(multiplicand[4]),
    .I2(_141_),
    .O(_001_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _156_ (
    .I0(multiplicand[6]),
    .I1(multiplicand[5]),
    .I2(_141_),
    .O(_001_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _157_ (
    .I0(multiplicand[7]),
    .I1(multiplicand[6]),
    .I2(_141_),
    .O(_001_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _158_ (
    .I0(multiplicand[8]),
    .I1(multiplicand[7]),
    .I2(_141_),
    .O(_001_[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _159_ (
    .I0(multiplicand[9]),
    .I1(multiplicand[8]),
    .I2(_141_),
    .O(_001_[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _160_ (
    .I0(multiplicand[10]),
    .I1(multiplicand[9]),
    .I2(_141_),
    .O(_001_[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _161_ (
    .I0(multiplicand[11]),
    .I1(multiplicand[10]),
    .I2(_141_),
    .O(_001_[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _162_ (
    .I0(multiplicand[12]),
    .I1(multiplicand[11]),
    .I2(_141_),
    .O(_001_[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _163_ (
    .I0(multiplicand[13]),
    .I1(multiplicand[12]),
    .I2(_141_),
    .O(_001_[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _164_ (
    .I0(multiplicand[14]),
    .I1(multiplicand[13]),
    .I2(_141_),
    .O(_001_[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'hca)
  ) _165_ (
    .I0(multiplicand[15]),
    .I1(multiplicand[14]),
    .I2(_141_),
    .O(_001_[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd3433754864)
  ) _166_ (
    .I0(_020_),
    .I1(_004_),
    .I2(p[0]),
    .I3(_142_),
    .I4(_141_),
    .O(_002_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56" *)
  LUT6 #(
    .INIT(64'h1000000000000000)
  ) _167_ (
    .I0(ctr[3]),
    .I1(ctr[4]),
    .I2(multiplier[7]),
    .I3(ctr[2]),
    .I4(ctr[1]),
    .I5(ctr[0]),
    .O(_142_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd3433754864)
  ) _168_ (
    .I0(_027_),
    .I1(_011_),
    .I2(p[1]),
    .I3(_142_),
    .I4(_141_),
    .O(_002_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd3433754864)
  ) _169_ (
    .I0(_028_),
    .I1(_012_),
    .I2(p[2]),
    .I3(_142_),
    .I4(_141_),
    .O(_002_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd3433754864)
  ) _170_ (
    .I0(_029_),
    .I1(_013_),
    .I2(p[3]),
    .I3(_142_),
    .I4(_141_),
    .O(_002_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd3433754864)
  ) _171_ (
    .I0(_030_),
    .I1(_014_),
    .I2(p[4]),
    .I3(_142_),
    .I4(_141_),
    .O(_002_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd3433754864)
  ) _172_ (
    .I0(_031_),
    .I1(_015_),
    .I2(p[5]),
    .I3(_142_),
    .I4(_141_),
    .O(_002_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd3433754864)
  ) _173_ (
    .I0(_032_),
    .I1(_016_),
    .I2(p[6]),
    .I3(_142_),
    .I4(_141_),
    .O(_002_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd3433754864)
  ) _174_ (
    .I0(_033_),
    .I1(_017_),
    .I2(p[7]),
    .I3(_142_),
    .I4(_141_),
    .O(_002_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd3433754864)
  ) _175_ (
    .I0(_034_),
    .I1(_018_),
    .I2(p[8]),
    .I3(_142_),
    .I4(_141_),
    .O(_002_[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd3433754864)
  ) _176_ (
    .I0(_035_),
    .I1(_019_),
    .I2(p[9]),
    .I3(_142_),
    .I4(_141_),
    .O(_002_[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd3433754864)
  ) _177_ (
    .I0(_021_),
    .I1(_005_),
    .I2(p[10]),
    .I3(_142_),
    .I4(_141_),
    .O(_002_[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd3433754864)
  ) _178_ (
    .I0(_022_),
    .I1(_006_),
    .I2(p[11]),
    .I3(_142_),
    .I4(_141_),
    .O(_002_[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd3433754864)
  ) _179_ (
    .I0(_023_),
    .I1(_007_),
    .I2(p[12]),
    .I3(_142_),
    .I4(_141_),
    .O(_002_[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd3433754864)
  ) _180_ (
    .I0(_024_),
    .I1(_008_),
    .I2(p[13]),
    .I3(_142_),
    .I4(_141_),
    .O(_002_[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd3433754864)
  ) _181_ (
    .I0(_025_),
    .I1(_009_),
    .I2(p[14]),
    .I3(_142_),
    .I4(_141_),
    .O(_002_[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd3433754864)
  ) _182_ (
    .I0(_026_),
    .I1(_010_),
    .I2(p[15]),
    .I3(_142_),
    .I4(_141_),
    .O(_002_[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _183_ (
    .I0(b[0]),
    .I1(reset),
    .O(_109_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _184_ (
    .I0(reset),
    .I1(b[1]),
    .O(_111_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _185_ (
    .I0(reset),
    .I1(b[2]),
    .O(_112_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _186_ (
    .I0(reset),
    .I1(b[3]),
    .O(_113_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _187_ (
    .I0(reset),
    .I1(b[4]),
    .O(_114_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _188_ (
    .I0(reset),
    .I1(b[5]),
    .O(_115_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _189_ (
    .I0(reset),
    .I1(b[6]),
    .O(_116_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _190_ (
    .I0(reset),
    .I1(b[7]),
    .O(_110_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h4)
  ) _191_ (
    .I0(b[0]),
    .I1(reset),
    .O(_125_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h4)
  ) _192_ (
    .I0(b[1]),
    .I1(reset),
    .O(_127_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h4)
  ) _193_ (
    .I0(b[2]),
    .I1(reset),
    .O(_128_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h4)
  ) _194_ (
    .I0(b[3]),
    .I1(reset),
    .O(_129_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h4)
  ) _195_ (
    .I0(b[4]),
    .I1(reset),
    .O(_130_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h4)
  ) _196_ (
    .I0(b[5]),
    .I1(reset),
    .O(_131_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h4)
  ) _197_ (
    .I0(b[6]),
    .I1(reset),
    .O(_132_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h4)
  ) _198_ (
    .I0(b[7]),
    .I1(reset),
    .O(_126_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _199_ (
    .I0(reset),
    .I1(a[0]),
    .O(_117_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _200_ (
    .I0(reset),
    .I1(a[1]),
    .O(_118_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _201_ (
    .I0(reset),
    .I1(a[2]),
    .O(_119_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _202_ (
    .I0(reset),
    .I1(a[3]),
    .O(_120_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _203_ (
    .I0(reset),
    .I1(a[4]),
    .O(_121_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _204_ (
    .I0(reset),
    .I1(a[5]),
    .O(_122_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _205_ (
    .I0(reset),
    .I1(a[6]),
    .O(_123_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h8)
  ) _206_ (
    .I0(reset),
    .I1(a[7]),
    .O(_124_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h4)
  ) _207_ (
    .I0(a[0]),
    .I1(reset),
    .O(_133_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h4)
  ) _208_ (
    .I0(a[1]),
    .I1(reset),
    .O(_134_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h4)
  ) _209_ (
    .I0(a[2]),
    .I1(reset),
    .O(_135_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h4)
  ) _210_ (
    .I0(a[3]),
    .I1(reset),
    .O(_136_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h4)
  ) _211_ (
    .I0(a[4]),
    .I1(reset),
    .O(_137_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h4)
  ) _212_ (
    .I0(a[5]),
    .I1(reset),
    .O(_138_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h4)
  ) _213_ (
    .I0(a[6]),
    .I1(reset),
    .O(_139_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'h4)
  ) _214_ (
    .I0(a[7]),
    .I1(reset),
    .O(_140_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:38" *)
  LUT2 #(
    .INIT(4'hb)
  ) _215_ (
    .I0(rdy),
    .I1(_141_),
    .O(_003_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16777216)
  ) _216_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[0]),
    .I4(p[0]),
    .O(_072_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:62" *)
  LUT6 #(
    .INIT(64'h0000000000000000)
  ) _217_ (
    .I0(multiplier[7]),
    .I1(multiplier[5]),
    .I2(multiplier[3]),
    .I3(multiplier[1]),
    .I4(ctr[1]),
    .I5(ctr[2]),
    .O(_105_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:65" *)
  LUT6 #(
    .INIT(64'h555533330f0f00ff)
  ) _218_ (
    .I0(multiplier[7]),
    .I1(multiplier[5]),
    .I2(multiplier[3]),
    .I3(multiplier[1]),
    .I4(ctr[1]),
    .I5(ctr[2]),
    .O(_106_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:68" *)
  MUXF7 _219_ (
    .I0(_105_),
    .I1(_106_),
    .O(_143_),
    .S(ctr[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:62" *)
  LUT6 #(
    .INIT(64'h00000f0f000000ff)
  ) _220_ (
    .I0(multiplier[6]),
    .I1(multiplier[4]),
    .I2(multiplier[2]),
    .I3(multiplier[0]),
    .I4(ctr[0]),
    .I5(ctr[1]),
    .O(_107_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:65" *)
  LUT6 #(
    .INIT(64'h0000555500003333)
  ) _221_ (
    .I0(multiplier[6]),
    .I1(multiplier[4]),
    .I2(multiplier[2]),
    .I3(multiplier[0]),
    .I4(ctr[0]),
    .I5(ctr[1]),
    .O(_108_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:68" *)
  MUXF7 _222_ (
    .I0(_107_),
    .I1(_108_),
    .O(_144_),
    .S(ctr[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16777216)
  ) _223_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[1]),
    .I4(p[1]),
    .O(_078_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16777216)
  ) _224_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[2]),
    .I4(p[2]),
    .O(_079_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16777216)
  ) _225_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[3]),
    .I4(p[3]),
    .O(_080_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16777216)
  ) _226_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[4]),
    .I4(p[4]),
    .O(_081_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16777216)
  ) _227_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[5]),
    .I4(p[5]),
    .O(_082_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16777216)
  ) _228_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[6]),
    .I4(p[6]),
    .O(_083_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16777216)
  ) _229_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[7]),
    .I4(p[7]),
    .O(_084_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16777216)
  ) _230_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[8]),
    .I4(p[8]),
    .O(_085_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16777216)
  ) _231_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[9]),
    .I4(p[9]),
    .O(_086_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16777216)
  ) _232_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[10]),
    .I4(p[10]),
    .O(_073_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16777216)
  ) _233_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[11]),
    .I4(p[11]),
    .O(_074_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16777216)
  ) _234_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[12]),
    .I4(p[12]),
    .O(_075_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16777216)
  ) _235_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[13]),
    .I4(p[13]),
    .O(_076_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16777216)
  ) _236_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[14]),
    .I4(p[14]),
    .O(_077_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16842495)
  ) _237_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[0]),
    .I4(p[0]),
    .O(_056_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16842495)
  ) _238_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[1]),
    .I4(p[1]),
    .O(_063_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16842495)
  ) _239_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[2]),
    .I4(p[2]),
    .O(_064_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16842495)
  ) _240_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[3]),
    .I4(p[3]),
    .O(_065_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16842495)
  ) _241_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[4]),
    .I4(p[4]),
    .O(_066_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16842495)
  ) _242_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[5]),
    .I4(p[5]),
    .O(_067_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16842495)
  ) _243_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[6]),
    .I4(p[6]),
    .O(_068_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16842495)
  ) _244_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[7]),
    .I4(p[7]),
    .O(_069_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16842495)
  ) _245_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[8]),
    .I4(p[8]),
    .O(_070_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16842495)
  ) _246_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[9]),
    .I4(p[9]),
    .O(_071_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16842495)
  ) _247_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[10]),
    .I4(p[10]),
    .O(_057_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16842495)
  ) _248_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[11]),
    .I4(p[11]),
    .O(_058_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16842495)
  ) _249_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[12]),
    .I4(p[12]),
    .O(_059_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16842495)
  ) _250_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[13]),
    .I4(p[13]),
    .O(_060_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16842495)
  ) _251_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[14]),
    .I4(p[14]),
    .O(_061_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd16842495)
  ) _252_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[15]),
    .I4(p[15]),
    .O(_062_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124544)
  ) _253_ (
    .I0(_144_),
    .I1(ctr[3]),
    .I2(_143_),
    .I3(multiplicand[0]),
    .I4(p[0]),
    .O(_041_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124544)
  ) _254_ (
    .I0(_144_),
    .I1(ctr[3]),
    .I2(_143_),
    .I3(multiplicand[1]),
    .I4(p[1]),
    .O(_047_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124544)
  ) _255_ (
    .I0(_144_),
    .I1(ctr[3]),
    .I2(_143_),
    .I3(multiplicand[2]),
    .I4(p[2]),
    .O(_048_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124544)
  ) _256_ (
    .I0(_144_),
    .I1(ctr[3]),
    .I2(_143_),
    .I3(multiplicand[3]),
    .I4(p[3]),
    .O(_049_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124544)
  ) _257_ (
    .I0(_144_),
    .I1(ctr[3]),
    .I2(_143_),
    .I3(multiplicand[4]),
    .I4(p[4]),
    .O(_050_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124544)
  ) _258_ (
    .I0(_144_),
    .I1(ctr[3]),
    .I2(_143_),
    .I3(multiplicand[5]),
    .I4(p[5]),
    .O(_051_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124544)
  ) _259_ (
    .I0(_144_),
    .I1(ctr[3]),
    .I2(_143_),
    .I3(multiplicand[6]),
    .I4(p[6]),
    .O(_052_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124544)
  ) _260_ (
    .I0(_144_),
    .I1(ctr[3]),
    .I2(_143_),
    .I3(multiplicand[7]),
    .I4(p[7]),
    .O(_053_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124544)
  ) _261_ (
    .I0(_144_),
    .I1(ctr[3]),
    .I2(_143_),
    .I3(multiplicand[8]),
    .I4(p[8]),
    .O(_054_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124544)
  ) _262_ (
    .I0(_144_),
    .I1(ctr[3]),
    .I2(_143_),
    .I3(multiplicand[9]),
    .I4(p[9]),
    .O(_055_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124544)
  ) _263_ (
    .I0(_144_),
    .I1(ctr[3]),
    .I2(_143_),
    .I3(multiplicand[10]),
    .I4(p[10]),
    .O(_042_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124544)
  ) _264_ (
    .I0(_144_),
    .I1(ctr[3]),
    .I2(_143_),
    .I3(multiplicand[11]),
    .I4(p[11]),
    .O(_043_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124544)
  ) _265_ (
    .I0(_144_),
    .I1(ctr[3]),
    .I2(_143_),
    .I3(multiplicand[12]),
    .I4(p[12]),
    .O(_044_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124544)
  ) _266_ (
    .I0(_144_),
    .I1(ctr[3]),
    .I2(_143_),
    .I3(multiplicand[13]),
    .I4(p[13]),
    .O(_045_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124544)
  ) _267_ (
    .I0(_144_),
    .I1(ctr[3]),
    .I2(_143_),
    .I3(multiplicand[14]),
    .I4(p[14]),
    .O(_046_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:34" *)
  LUT1 #(
    .INIT(2'h1)
  ) _268_ (
    .I0(ctr[0]),
    .O(_103_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:34" *)
  LUT1 #(
    .INIT(2'h1)
  ) _269_ (
    .I0(ctr[4]),
    .O(_040_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:34" *)
  LUT1 #(
    .INIT(2'h1)
  ) _270_ (
    .I0(ctr[2]),
    .O(_038_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:34" *)
  LUT1 #(
    .INIT(2'h1)
  ) _271_ (
    .I0(ctr[1]),
    .O(_037_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:34" *)
  LUT1 #(
    .INIT(2'h1)
  ) _272_ (
    .I0(ctr[3]),
    .O(_039_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124800)
  ) _273_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[0]),
    .I4(p[0]),
    .O(_087_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124800)
  ) _274_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[1]),
    .I4(p[1]),
    .O(_094_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124800)
  ) _275_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[2]),
    .I4(p[2]),
    .O(_095_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124800)
  ) _276_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[3]),
    .I4(p[3]),
    .O(_096_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124800)
  ) _277_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[4]),
    .I4(p[4]),
    .O(_097_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124800)
  ) _278_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[5]),
    .I4(p[5]),
    .O(_098_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124800)
  ) _279_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[6]),
    .I4(p[6]),
    .O(_099_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124800)
  ) _280_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[7]),
    .I4(p[7]),
    .O(_100_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124800)
  ) _281_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[8]),
    .I4(p[8]),
    .O(_101_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124800)
  ) _282_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[9]),
    .I4(p[9]),
    .O(_102_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124800)
  ) _283_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[10]),
    .I4(p[10]),
    .O(_088_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124800)
  ) _284_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[11]),
    .I4(p[11]),
    .O(_089_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124800)
  ) _285_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[12]),
    .I4(p[12]),
    .O(_090_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124800)
  ) _286_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[13]),
    .I4(p[13]),
    .O(_091_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124800)
  ) _287_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[14]),
    .I4(p[14]),
    .O(_092_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd4278124800)
  ) _288_ (
    .I0(_143_),
    .I1(_144_),
    .I2(ctr[3]),
    .I3(multiplicand[15]),
    .I4(p[15]),
    .O(_093_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:34" *)
  LUT1 #(
    .INIT(2'h1)
  ) _289_ (
    .I0(ctr[0]),
    .O(_036_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:76|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _290_ (
    .CI(1'h1),
    .DI(1'h0),
    .O(_145_[1]),
    .S(_036_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:76|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _291_ (
    .CI(_145_[1]),
    .DI(1'h0),
    .O(_145_[2]),
    .S(_037_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:76|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _292_ (
    .CI(_145_[2]),
    .DI(1'h0),
    .O(_145_[3]),
    .S(_038_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:76|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _293_ (
    .CI(_145_[3]),
    .DI(_039_),
    .O(_145_[4]),
    .S(ctr[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:76|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _294_ (
    .CI(_145_[4]),
    .DI(1'h0),
    .O(_104_),
    .S(_040_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _295_ (
    .CI(1'h1),
    .DI(_041_),
    .O(_146_[1]),
    .S(_056_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _296_ (
    .CI(1'h1),
    .LI(_056_),
    .O(_004_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _297_ (
    .CI(_146_[10]),
    .DI(_042_),
    .O(_146_[11]),
    .S(_057_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _298_ (
    .CI(_146_[10]),
    .LI(_057_),
    .O(_005_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _299_ (
    .CI(_146_[11]),
    .DI(_043_),
    .O(_146_[12]),
    .S(_058_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _300_ (
    .CI(_146_[11]),
    .LI(_058_),
    .O(_006_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _301_ (
    .CI(_146_[12]),
    .DI(_044_),
    .O(_146_[13]),
    .S(_059_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _302_ (
    .CI(_146_[12]),
    .LI(_059_),
    .O(_007_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _303_ (
    .CI(_146_[13]),
    .DI(_045_),
    .O(_146_[14]),
    .S(_060_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _304_ (
    .CI(_146_[13]),
    .LI(_060_),
    .O(_008_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _305_ (
    .CI(_146_[14]),
    .DI(_046_),
    .O(_146_[15]),
    .S(_061_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _306_ (
    .CI(_146_[14]),
    .LI(_061_),
    .O(_009_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _307_ (
    .CI(_146_[15]),
    .LI(_062_),
    .O(_010_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _308_ (
    .CI(_146_[1]),
    .DI(_047_),
    .O(_146_[2]),
    .S(_063_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _309_ (
    .CI(_146_[1]),
    .LI(_063_),
    .O(_011_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _310_ (
    .CI(_146_[2]),
    .DI(_048_),
    .O(_146_[3]),
    .S(_064_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _311_ (
    .CI(_146_[2]),
    .LI(_064_),
    .O(_012_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _312_ (
    .CI(_146_[3]),
    .DI(_049_),
    .O(_146_[4]),
    .S(_065_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _313_ (
    .CI(_146_[3]),
    .LI(_065_),
    .O(_013_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _314_ (
    .CI(_146_[4]),
    .DI(_050_),
    .O(_146_[5]),
    .S(_066_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _315_ (
    .CI(_146_[4]),
    .LI(_066_),
    .O(_014_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _316_ (
    .CI(_146_[5]),
    .DI(_051_),
    .O(_146_[6]),
    .S(_067_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _317_ (
    .CI(_146_[5]),
    .LI(_067_),
    .O(_015_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _318_ (
    .CI(_146_[6]),
    .DI(_052_),
    .O(_146_[7]),
    .S(_068_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _319_ (
    .CI(_146_[6]),
    .LI(_068_),
    .O(_016_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _320_ (
    .CI(_146_[7]),
    .DI(_053_),
    .O(_146_[8]),
    .S(_069_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _321_ (
    .CI(_146_[7]),
    .LI(_069_),
    .O(_017_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _322_ (
    .CI(_146_[8]),
    .DI(_054_),
    .O(_146_[9]),
    .S(_070_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _323_ (
    .CI(_146_[8]),
    .LI(_070_),
    .O(_018_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _324_ (
    .CI(_146_[9]),
    .DI(_055_),
    .O(_146_[10]),
    .S(_071_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:125|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _325_ (
    .CI(_146_[9]),
    .LI(_071_),
    .O(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _326_ (
    .CI(1'h0),
    .DI(_072_),
    .O(_147_[1]),
    .S(_087_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _327_ (
    .CI(1'h0),
    .LI(_087_),
    .O(_020_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _328_ (
    .CI(_147_[10]),
    .DI(_073_),
    .O(_147_[11]),
    .S(_088_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _329_ (
    .CI(_147_[10]),
    .LI(_088_),
    .O(_021_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _330_ (
    .CI(_147_[11]),
    .DI(_074_),
    .O(_147_[12]),
    .S(_089_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _331_ (
    .CI(_147_[11]),
    .LI(_089_),
    .O(_022_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _332_ (
    .CI(_147_[12]),
    .DI(_075_),
    .O(_147_[13]),
    .S(_090_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _333_ (
    .CI(_147_[12]),
    .LI(_090_),
    .O(_023_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _334_ (
    .CI(_147_[13]),
    .DI(_076_),
    .O(_147_[14]),
    .S(_091_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _335_ (
    .CI(_147_[13]),
    .LI(_091_),
    .O(_024_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _336_ (
    .CI(_147_[14]),
    .DI(_077_),
    .O(_147_[15]),
    .S(_092_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _337_ (
    .CI(_147_[14]),
    .LI(_092_),
    .O(_025_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _338_ (
    .CI(_147_[15]),
    .LI(_093_),
    .O(_026_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _339_ (
    .CI(_147_[1]),
    .DI(_078_),
    .O(_147_[2]),
    .S(_094_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _340_ (
    .CI(_147_[1]),
    .LI(_094_),
    .O(_027_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _341_ (
    .CI(_147_[2]),
    .DI(_079_),
    .O(_147_[3]),
    .S(_095_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _342_ (
    .CI(_147_[2]),
    .LI(_095_),
    .O(_028_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _343_ (
    .CI(_147_[3]),
    .DI(_080_),
    .O(_147_[4]),
    .S(_096_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _344_ (
    .CI(_147_[3]),
    .LI(_096_),
    .O(_029_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _345_ (
    .CI(_147_[4]),
    .DI(_081_),
    .O(_147_[5]),
    .S(_097_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _346_ (
    .CI(_147_[4]),
    .LI(_097_),
    .O(_030_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _347_ (
    .CI(_147_[5]),
    .DI(_082_),
    .O(_147_[6]),
    .S(_098_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _348_ (
    .CI(_147_[5]),
    .LI(_098_),
    .O(_031_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _349_ (
    .CI(_147_[6]),
    .DI(_083_),
    .O(_147_[7]),
    .S(_099_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _350_ (
    .CI(_147_[6]),
    .LI(_099_),
    .O(_032_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _351_ (
    .CI(_147_[7]),
    .DI(_084_),
    .O(_147_[8]),
    .S(_100_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _352_ (
    .CI(_147_[7]),
    .LI(_100_),
    .O(_033_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _353_ (
    .CI(_147_[8]),
    .DI(_085_),
    .O(_147_[9]),
    .S(_101_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _354_ (
    .CI(_147_[8]),
    .LI(_101_),
    .O(_034_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _355_ (
    .CI(_147_[9]),
    .DI(_086_),
    .O(_147_[10]),
    .S(_102_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:126|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _356_ (
    .CI(_147_[9]),
    .LI(_102_),
    .O(_035_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:89|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _357_ (
    .CI(1'h0),
    .DI(ctr[0]),
    .O(_148_[1]),
    .S(_103_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:89|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _358_ (
    .CI(1'h0),
    .LI(_103_),
    .O(_000_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:89|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _359_ (
    .CI(_148_[1]),
    .DI(1'h0),
    .O(_148_[2]),
    .S(ctr[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:89|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _360_ (
    .CI(_148_[1]),
    .LI(ctr[1]),
    .O(_000_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:89|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _361_ (
    .CI(_148_[2]),
    .DI(1'h0),
    .O(_148_[3]),
    .S(ctr[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:89|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _362_ (
    .CI(_148_[2]),
    .LI(ctr[2]),
    .O(_000_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:89|/usr/bin/../share/yosys/xilinx/arith_map.v:342" *)
  MUXCY _363_ (
    .CI(_148_[3]),
    .DI(1'h0),
    .O(_148_[4]),
    .S(ctr[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:89|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _364_ (
    .CI(_148_[3]),
    .LI(ctr[3]),
    .O(_000_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:89|/usr/bin/../share/yosys/xilinx/arith_map.v:348" *)
  XORCY _365_ (
    .CI(_148_[4]),
    .LI(ctr[4]),
    .O(_000_[4])
  );
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _109_ or posedge _125_)
    if (_125_)
      multiplicand[0] <= 0;
    else if (_109_)
      multiplicand[0] <= 1;
    else
      multiplicand[0] <= _001_[0];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _111_ or posedge _127_)
    if (_127_)
      multiplicand[1] <= 0;
    else if (_111_)
      multiplicand[1] <= 1;
    else
      multiplicand[1] <= _001_[1];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _112_ or posedge _128_)
    if (_128_)
      multiplicand[2] <= 0;
    else if (_112_)
      multiplicand[2] <= 1;
    else
      multiplicand[2] <= _001_[2];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _113_ or posedge _129_)
    if (_129_)
      multiplicand[3] <= 0;
    else if (_113_)
      multiplicand[3] <= 1;
    else
      multiplicand[3] <= _001_[3];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _114_ or posedge _130_)
    if (_130_)
      multiplicand[4] <= 0;
    else if (_114_)
      multiplicand[4] <= 1;
    else
      multiplicand[4] <= _001_[4];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _115_ or posedge _131_)
    if (_131_)
      multiplicand[5] <= 0;
    else if (_115_)
      multiplicand[5] <= 1;
    else
      multiplicand[5] <= _001_[5];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _116_ or posedge _132_)
    if (_132_)
      multiplicand[6] <= 0;
    else if (_116_)
      multiplicand[6] <= 1;
    else
      multiplicand[6] <= _001_[6];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _110_ or posedge _126_)
    if (_126_)
      multiplicand[7] <= 0;
    else if (_110_)
      multiplicand[7] <= 1;
    else
      multiplicand[7] <= _001_[7];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _110_ or posedge _126_)
    if (_126_)
      multiplicand[8] <= 0;
    else if (_110_)
      multiplicand[8] <= 1;
    else
      multiplicand[8] <= _001_[8];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _110_ or posedge _126_)
    if (_126_)
      multiplicand[9] <= 0;
    else if (_110_)
      multiplicand[9] <= 1;
    else
      multiplicand[9] <= _001_[9];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _110_ or posedge _126_)
    if (_126_)
      multiplicand[10] <= 0;
    else if (_110_)
      multiplicand[10] <= 1;
    else
      multiplicand[10] <= _001_[10];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _110_ or posedge _126_)
    if (_126_)
      multiplicand[11] <= 0;
    else if (_110_)
      multiplicand[11] <= 1;
    else
      multiplicand[11] <= _001_[11];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _110_ or posedge _126_)
    if (_126_)
      multiplicand[12] <= 0;
    else if (_110_)
      multiplicand[12] <= 1;
    else
      multiplicand[12] <= _001_[12];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _110_ or posedge _126_)
    if (_126_)
      multiplicand[13] <= 0;
    else if (_110_)
      multiplicand[13] <= 1;
    else
      multiplicand[13] <= _001_[13];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _110_ or posedge _126_)
    if (_126_)
      multiplicand[14] <= 0;
    else if (_110_)
      multiplicand[14] <= 1;
    else
      multiplicand[14] <= _001_[14];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _110_ or posedge _126_)
    if (_126_)
      multiplicand[15] <= 0;
    else if (_110_)
      multiplicand[15] <= 1;
    else
      multiplicand[15] <= _001_[15];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _117_ or posedge _133_)
    if (_133_)
      multiplier[0] <= 0;
    else if (_117_)
      multiplier[0] <= 1;
    else
      multiplier[0] <= multiplier[0];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _118_ or posedge _134_)
    if (_134_)
      multiplier[1] <= 0;
    else if (_118_)
      multiplier[1] <= 1;
    else
      multiplier[1] <= multiplier[1];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _119_ or posedge _135_)
    if (_135_)
      multiplier[2] <= 0;
    else if (_119_)
      multiplier[2] <= 1;
    else
      multiplier[2] <= multiplier[2];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _120_ or posedge _136_)
    if (_136_)
      multiplier[3] <= 0;
    else if (_120_)
      multiplier[3] <= 1;
    else
      multiplier[3] <= multiplier[3];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _121_ or posedge _137_)
    if (_137_)
      multiplier[4] <= 0;
    else if (_121_)
      multiplier[4] <= 1;
    else
      multiplier[4] <= multiplier[4];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _122_ or posedge _138_)
    if (_138_)
      multiplier[5] <= 0;
    else if (_122_)
      multiplier[5] <= 1;
    else
      multiplier[5] <= multiplier[5];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _123_ or posedge _139_)
    if (_139_)
      multiplier[6] <= 0;
    else if (_123_)
      multiplier[6] <= 1;
    else
      multiplier[6] <= multiplier[6];
  (* src = "seq_mult.v:62" *)
  always @(posedge clk or posedge _124_ or posedge _140_)
    if (_140_)
      multiplier[7] <= 0;
    else if (_124_)
      multiplier[7] <= 1;
    else
      multiplier[7] <= multiplier[7];
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _390_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_000_[0]),
    .Q(ctr[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _391_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_000_[1]),
    .Q(ctr[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _392_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_000_[2]),
    .Q(ctr[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _393_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_000_[3]),
    .Q(ctr[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _394_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_000_[4]),
    .Q(ctr[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _395_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_002_[0]),
    .Q(p[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _396_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_002_[1]),
    .Q(p[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _397_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_002_[2]),
    .Q(p[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _398_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_002_[3]),
    .Q(p[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _399_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_002_[4]),
    .Q(p[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _400_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_002_[5]),
    .Q(p[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _401_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_002_[6]),
    .Q(p[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _402_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_002_[7]),
    .Q(p[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _403_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_002_[8]),
    .Q(p[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _404_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_002_[9]),
    .Q(p[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _405_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_002_[10]),
    .Q(p[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _406_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_002_[11]),
    .Q(p[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _407_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_002_[12]),
    .Q(p[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _408_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_002_[13]),
    .Q(p[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _409_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_002_[14]),
    .Q(p[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _410_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_002_[15]),
    .Q(p[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "seq_mult.v:62|/usr/bin/../share/yosys/xilinx/ff_map.v:34" *)
  FDCE #(
    .INIT(1'h0)
  ) _411_ (
    .C(clk),
    .CE(1'h1),
    .CLR(reset),
    .D(_003_),
    .Q(rdy)
  );
  assign _145_[0] = 1'h1;
  assign _146_[0] = 1'h1;
  assign _147_[0] = 1'h0;
  assign _148_[0] = 1'h0;
  assign acc_in2 = p;
  assign mux_in1 = multiplicand;
  assign mux_in2 = 16'h0000;
endmodule
